[package]
name = "rust_examle"
version = "0.1.0"
authors = ["Sandeepan <sandyc372@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
iced = "0.1"
libmath = "0.2.1"